### ISSUE TITLE
Alexandria can steal other cards

### ISSUE THREAD

**Issue by TakeWalker** [jamespicone/potw#36]
Using her base power with Idol of Anput (from Tomb of Anubis) in play let her take it into her hand. This shouldn't happen as, as written, the power and her other abilities only care about cards she owns.

**Comment by jamespicone** [comment]
Thanks for the excellent bug report. https://github.com/jamespicone/potw/commit/4ba8396153468ae9d8f372fc089a93ea2aaeb7c4 should fix this one, modulo cards that change owner (and arguably Alexandria should be able to put those into her hand)
