### ISSUE TITLE
Dauntless Outfitting deletes cards if it doesn't find a target to put into play

### ISSUE THREAD

**Issue by ZeroTakenaka** [jamespicone/potw#45]
I'm not sure if this is exactly right but I was playing Dauntless. I had Arcstep in play. Arcshield in my hand. There were no other equipment or relics in my deck. I played Outfitting and the game went through Dauntless's deck and revealed no playable targets. All the revealed cards were then immediately removed from the game and not put into the trash or back on to the deck.

**Comment by jamespicone** [comment]
Thanks for the report! Should be fixed in https://github.com/jamespicone/potw/commit/718b288fac51f2cb7defcfb45e9f2da46381310d
